// <auto-generated />
using System;
using Loan.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Loan.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260807143342_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Loan.Domain.Entities.LoanItem", b =>
                {
                    b.Property<Guid>("LoanRegistryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoanRegistryId1")
                        .HasColumnType("uuid");

                    b.HasKey("LoanRegistryId", "BookId");

                    b.HasIndex("LoanRegistryId1");

                    b.ToTable("LoanItem", (string)null);
                });

            modelBuilder.Entity("Loan.Domain.Entities.LoanRegistry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("LoanDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ReturnedDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("LoanRegistry", (string)null);
                });

            modelBuilder.Entity("Loan.Domain.Entities.LoanItem", b =>
                {
                    b.HasOne("Loan.Domain.Entities.LoanRegistry", null)
                        .WithMany("Items")
                        .HasForeignKey("LoanRegistryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loan.Domain.Entities.LoanRegistry", "LoanRegistry")
                        .WithMany("_items")
                        .HasForeignKey("LoanRegistryId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanRegistry");
                });

            modelBuilder.Entity("Loan.Domain.Entities.LoanRegistry", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("_items");
                });
#pragma warning restore 612, 618
        }
    }
}
